[package]
name = "rbgn"
version = "0.1.0"
edition = "2021"
authors = ["romw314"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive", "cargo"] }
linereader = "0.4.0"
