name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: ningenMe/setup-rustup@v1.1.0
      with:
        rust-version: 1.75
    - name: Build
      run: cargo build
  test:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: ningenMe/setup-rustup@v1.1.0
      with:
        rust-version: 1.75
    - name: Run tests
      run: cargo test
